# Generated by Django 5.1 on 2024-08-29 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publisher',
            new_name='published_at',
        ),
    ]
